#!/usr/bin/perl
# Writes theme-words.js from themes.txt: every word that counts as a theme
# word, per theme. The game checks each word a player spells against its
# day's list, so any word on it scores the theme bonus wherever it's played.
#
#   perl gen-theme-words.pl
#
# Adding words here (and re-running this) never changes a puzzle: the calendar
# (daily-calendar.js) is only rebuilt by gen-calendar.pl.
use strict; use warnings;

open my $in, '<:raw', 'themes.txt' or die "themes.txt: $!";
my (%words, @order, $cur);
while (my $l = <$in>) {
  if ($l =~ /^== (\w+) \|/) { $cur = $1; push @order, $cur; $words{$cur} = {}; next; }
  next if !$cur || $l =~ /^\s*(#|@|$)/;
  $words{$cur}{$_} = 1 for grep { /^[a-z]{4,}$/ } split ' ', $l;
}
close $in;

open my $out, '>:raw', 'theme-words.js' or die "theme-words.js: $!";
print $out "// Theme words, per theme: spelling any of them on that theme's day scores\n";
print $out "// a bonus point. Generated by gen-theme-words.pl from themes.txt - do not hand-edit.\n";
print $out "window.THEME_WORDS = {\n";
print $out "$_: \"" . join(' ', sort keys %{ $words{$_} }) . "\",\n" for @order;
print $out "};\n";
close $out;
my $n = 0; $n += keys %{ $words{$_} } for @order;
print scalar(@order), " themes, $n words -> theme-words.js\n";
