use strict;
use warnings;

# Builds daily-pool.js: the climbs the themed daily calendar picks from, with
# peaks of 7, 9, 10 and 11 letters. (8-letter peaks come from climbs.js, which
# stays exactly as it is so Adventure Mode's numbering never moves.)
# Same rules as gen-climbs.pl, at any length:
#   - every rung is an everyday word (freq.js), starting at 3 letters
#   - +1 letter per rung, no rung is the one below plus -s (or -d/-r/-n on an -e word)
#   - one climb per qualifying top word, most common word chosen at each rung
#   - no lockouts: whatever valid word a player picks, the next rung stays solvable
#   - no word from climb-blocklist.txt anywhere in a climb (blocked words are
#     taken out before the climbs are built, so a climb can route around one)
# This file is a build input for the calendar builder; the game doesn't load it.

my $DIR = 'D:/Claude Code/portfolio/games/3-2-1';
my $OUT = "$DIR/daily-pool.js";
my @PEAKS = (7, 9, 10, 11);
my $MAXLEN = 11;

sub load {
    my ($path) = @_;
    open(my $fh, '<', $path) or die "$path: $!";
    my (%w, @order);
    while (my $l = <$fh>) {
        $l =~ s/\s+$//;
        next unless $l =~ /^[a-z]+$/;
        my $n = length $l;
        next if $n < 3 || $n > $MAXLEN;
        push @order, $l unless $w{$l}++;
    }
    close $fh;
    return (\%w, \@order);
}
sub keyf { join('', sort split //, $_[0]) }
sub forbidden {
    my ($s, $l) = @_;
    return 1 if $l eq $s . 's';
    if ($s =~ /e$/) { return 1 if $l eq $s.'d' || $l eq $s.'r' || $l eq $s.'n'; }
    return 0;
}

my ($freq, $forder) = load("$DIR/freq.js");     # "everyday word"
my ($enable)        = load("$DIR/words.js");    # every word a player may type

# blocklist: one word per line, # starts a comment
my %blocked;
if (open(my $bf, '<', "$DIR/climb-blocklist.txt")) {
    while (<$bf>) { s/#.*//; s/\s+//g; $blocked{lc $_} = 1 if length; }
    close $bf;
}
delete $freq->{$_} for keys %blocked;
my %rank; my $r = 0; $rank{$_} = $r++ for grep { $freq->{$_} } @$forder;

my (%fbk, %ebk, @byLen);
push @{ $fbk{ keyf($_) } }, $_ for keys %$freq;
push @{ $ebk{ keyf($_) } }, $_ for keys %$enable;
push @{ $byLen[ length $_ ] }, $_ for keys %$freq;

sub preds {
    my ($L) = @_;
    my $key = keyf($L);
    my (%seen, %got);
    my @ch = split //, $key;
    for my $i (0 .. $#ch) {
        next if $seen{ $ch[$i] }++;
        my $sub = $key; substr($sub, $i, 1) = '';
        $got{$_} = 1 for @{ $fbk{$sub} || [] };
    }
    return keys %got;
}

# reachability up from 3 letters, no forbidden steps
my (%ok, %pred);
$ok{$_} = 1 for @{ $byLen[3] };
for my $k (4 .. $MAXLEN) {
    for my $L (@{ $byLen[$k] || [] }) {
        for my $S (preds($L)) {
            next unless $ok{$S};
            next if forbidden($S, $L);
            $ok{$L} = 1;
            push @{ $pred{$L} }, $S;
        }
    }
}
sub best_pred { my @c = sort { $rank{$a} <=> $rank{$b} or $a cmp $b } @_; $c[0] }

# lockout: follow every word a player could actually have played
sub lockout {
    my @c = @_;
    my %reach = map { $_ => 1 } @{ $ebk{ keyf($c[0]) } || [] };
    for my $i (1 .. $#c) {
        my @words = @{ $ebk{ keyf($c[$i]) } || [] };
        my %next;
        for my $p (keys %reach) {
            my @okw = grep { !forbidden($p, $_) } @words;
            return 1 unless @okw;
            $next{$_} = 1 for @okw;
        }
        %reach = %next;
    }
    return 0;
}

my (%rows, $locked);
for my $N (@PEAKS) {
    for my $top (sort @{ $byLen[$N] || [] }) {
        next unless $ok{$top};
        my @chain = ($top);
        my $cur = $top;
        while (length($cur) > 3) { $cur = best_pred(@{ $pred{$cur} }); push @chain, $cur; }
        @chain = reverse @chain;
        if (lockout(@chain)) { $locked++; next; }

        # sanity: N-2 words, each +1 letter, no forbidden step, all everyday words
        die "len $top" unless @chain == $N - 2;
        my @adds;
        for my $i (0 .. $#chain - 1) {
            die "notword $chain[$i]" unless $freq->{ $chain[$i] };
            die "forbidden $chain[$i]->$chain[$i+1]" if forbidden($chain[$i], $chain[$i+1]);
            my %h; $h{$_}++ for split //, $chain[$i+1];
            $h{$_}-- for split //, $chain[$i];
            my @extra = grep { $h{$_} != 0 } keys %h;
            die "diff $chain[$i]->$chain[$i+1]" unless @extra == 1 && $h{$extra[0]} == 1;
            push @adds, $extra[0];
        }
        push @{ $rows{$N} }, [ \@chain, \@adds ];
    }
}

open(my $o, '>', $OUT) or die "$OUT: $!";
print $o "// Themed-daily climb pool: peaks of 7, 9, 10 and 11 letters (8s live in climbs.js).\n";
print $o "// Generated by gen-daily-pool.pl - do not hand-edit; block words in climb-blocklist.txt.\n";
print $o "// Each: c = the reference ladder (3 letters up to the peak, +1 letter per rung),\n";
print $o "//       a = the letter added at each step. Players may answer any valid word.\n";
print $o "// Refer to climbs by their top word, not position: positions shift on regeneration.\n";
print $o "window.DAILY_POOL = {\n";
for my $N (@PEAKS) {
    print $o "$N: [\n";
    for my $row (@{ $rows{$N} || [] }) {
        my ($c, $a) = @$row;
        printf $o "{c:[%s],a:[%s]},\n", join(',', map { "\"$_\"" } @$c), join(',', map { "\"$_\"" } @$a);
    }
    print $o "],\n";
}
print $o "};\n";
close $o;

printf "wrote %s: %s | %d dropped for lockouts | %d blocked words\n", $OUT,
    join(", ", map { "$_-letter peaks " . scalar @{ $rows{$_} || [] } } @PEAKS), $locked || 0, scalar keys %blocked;
